cloudwalk/hermes-mcp

- lib/hermes/message.ex
- test/hermes/message_test.exs
We needed a robust way to validate and process Model Context Protocol (MCP) messages according to the schema specification.
This PR introduces the `Hermes.Message` module that:
- Defines specialized schemas for MCP protocol message validation
- Provides encoding/decoding functions for JSON-RPC messages
- Implements validation for all standard MCP message types (requests, notifications, responses, errors)
- Adds a comprehensive test suite to ensure proper handling of all message formats
1. **Schema Definition Approach**: We defined schemas for each message type and their parameters separately to allow for precise validation of the different MCP request and notification types.
2. **Dependent Validation**: Implemented smart parameter validation that changes based on the message method using …
> feat: rpc and mcp specific message parsing

- CLAUDE.md
- config/config.exs
- lib/hermes.ex
- lib/hermes/client.ex
- lib/hermes/transport/behaviour.ex
- lib/hermes/transport/sse.ex
- test/hermes/client_test.exs
- test/test_helper.exs
The current Hermes MCP implementation has limitations when handling multiple clients and transports with different names. The transport parameter design requires either a module name or PID, which doesn't provide clear separation between transport implementations and specific transport instances. This leads to issues when trying to use multiple instances of the same transport type with different configurations.
This PR refactors the transport handling in Hermes MCP by:
1. Changing the transport parameter from a direct reference (module or PID) to a structured map with `layer` and `name` keys
2. Modifying the client to use `transport.layer.send_message(transport.name, data)` instead of direct module calls
3. Removing the one-argument `send_message/1` optional callback from …
> feat: allow multiple client <> transport pairs

- lib/hermes/client.ex
- lib/hermes/sse.ex
- lib/hermes/transport/sse.ex
The Hermes MCP client was experiencing "Invalid session ID" errors when SSE connections were terminated unexpectedly or when attempting to shut down connections. This occurred because:
1. The SSE connection didn't properly handle reconnection when connections dropped
2. The client closure mechanism blocked when trying to close connections
3. Default timeouts were causing premature termination of long-lived SSE connections
These issues were documented in repo issues #11 and #22 related to graceful shutdown of SSE connections.
The implementation includes several key improvements:
1. Modified the client closure mechanism from a synchronous `handle_call(:close)` to an asynchronous `handle_cast(:close)` to prevent blocking
2. Added automatic reconnection logic with the new `loop_sse_stream` …
> feat: allow sse graceful shutdown and handle sse streaming reconnection

- lib/hermes/client.ex
- lib/hermes/mcp/response.ex
- pages/error_handling.md
- test/hermes/client_test.exs
- test/hermes/mcp/response_test.exs
Domain errors were being transformed from valid JSON-RPC responses into custom error
tuples, hiding the original response structure.
Return domain errors as successful responses with the is_error flag set to true,
preserving the complete original structure and allowing more flexibility in error
handling.
This approach maintains a clearer separation between protocol errors and domain-level
errors, giving clients more control over how to handle application-specific error
states.
> fix: do not handle domain errors

- lib/hermes/transport/sse.ex
- lib/hermes/uri.ex
- mix.exs
- test/hermes/uri_test.exs
The SSE transport had inconsistent URL path handling which caused connection issues
depending on how base_url and base_path were configured. Some configurations would work
for SSE initialization but break for message endpoints.
Created a new Hermes.URI module with standardized path joining logic that correctly
handles all combinations of base URLs and path segments with proper slash
normalization.
The simplified approach using path segment splitting and joining is more readable and
robust than complex string manipulation, avoiding edge cases with trailing and leading
slashes while ensuring consistent path construction.
> feat: improve sse uri path handling

- lib/hermes.ex
- lib/hermes/client.ex
- lib/hermes/http.ex
- lib/hermes/transport/sse.ex
- lib/mix/tasks/sse.interactive.ex
- test/test_helper.exs
We have a usecase that will have a number of mcp clients that is not knowable at compile time, which makes the static config this library is largely built around with its naming validation not as usable.
Introduced a custom validator for the full genserver name spec (as i remember it) and wires it in the transport and client.
see above
> Add support for registry-based names in client + http transport

- .env.dev
- .github/workflows/release.yml
- CONTRIBUTING.md
- README.md
- config/config.exs
- lib/hermes.ex
- lib/hermes/application.ex
- mix.exs
The CLI compilation process was inconsistent and the project lacked proper contribution
guidelines.
Added CONTRIBUTING.md, an environment flag to control CLI compilation, and updated configuration
to make CLI compilation more deterministic.
Using an environment variable (HERMES_MCP_COMPILE_CLI) provides a clear way to control when the
application should be built as a CLI vs. a library, improving flexibility for both development
and release workflows.
> improve cli compilation and setup/contribution guides

- .gitignore
- lib/hermes/client.ex
- lib/hermes/transport/sse.ex
- test/hermes/transport/sse_test.exs
The client was closing the transport connection in both handle_cast(:close) and terminate/2,
potentially causing duplicate termination attempts that could lead to race conditions.
Added a proper terminate/2 callback to the client that handles cleanup tasks previously done
in handle_cast(:close), including notifying of cancelled requests and shutting down the
transport layer.
By moving the cleanup logic to the terminate/2 callback, we ensure these operations happen
exactly once during the shutdown process, avoiding duplicate termination calls between the
client and transport layers.
> feat: implement termination cleanup on Hermes.Client

- README.md
In my first reading of `hermes-mcp`, I couldn't tell if it was meant to be a MCP client, or both MCP client and server.  (turns out it is the latter)  I hope this PR helps future readers avoid the same confusion.
In the README,  I change `## Features` to `## Roadmap`, using checkboxes to indicate what is done and what is planned.
I took a guess at a set of planned features.  Edit as you see fit.  ;-)
> doc: Add Roadmap to README

- lib/mix/interactive/ui.ex
The interactive CLI tools command didn't display schema information for MCP tools,
making it difficult for users to understand the required parameters and their types
when using tools.
Enhanced the UI module to pretty print tool schemas when listing tools, displaying
each parameter with its type, description, and whether it's required.
Used a hierarchical approach with helper functions to improve code readability and
maintainability. The implementation separates concerns by extracting schema
printing logic into dedicated helper functions, making the code more modular and
easier to extend in the future.
> feat: pretty print tool arguments on list_tools

- .github/workflows/ci.yml
Dialyzer PLT cache in CI workflow was being reset on every run, taking ~2 minutes
each time instead of using cached results.
Fixed the GitHub Actions cache configuration for dialyzer PLTs by:
1. Using a single cache action instead of separate restore/save steps
2. Including mix.lock hash in the cache key for proper dependency tracking
3. Adding better restore-keys fallback pattern
The previous implementation had issues with:
- Using separate restore/save actions (v3) rather than the simpler combined cache
action (v4)
- Not including dependency changes in the cache key
- Lack of fallback restore keys for partial matches
This implementation follows GitHub Actions best practices for caching and should
significantly speed up CI runs.
> fix: use mix.lock as cache key

- lib/mix/interactive/cli.ex
- lib/mix/interactive/commands.ex
- lib/mix/interactive/state.ex
- mix.exs
- pages/cli_usage.md
- pages/home.md
The interactive CLI lacked visibility into internal state, making it difficult to debug client
connections and understand system behavior. Users had no way to introspect the client and
transport processes during interactive sessions.
Implemented a new "show_state" command that displays the internal state of Hermes.Client and
Hermes.Transport processes. Created a dedicated Mix.Interactive.State module with specialized
formatting for different transport types (SSE/STDIO) and added support for verbose mode via
flag/env variable.
Used a modular approach with separate formatting module to maintain clean separation of
concerns. Leveraged Erlang's :sys.get_state/1 for non-intrusive state inspection. Implemented
both normal and verbose modes to support different debugging needs while keeping the …
> feat: add internal client/transport state inspect on cli/mix tasks

- .env.dev
- .github/workflows/ci.yml
- config/config.exs
- lib/hermes/client.ex
- lib/hermes/http.ex
- lib/hermes/logging.ex
- lib/hermes/sse.ex
- lib/hermes/transport/sse.ex
- lib/hermes/transport/stdio.ex
- lib/mix/interactive/cli.ex
- lib/mix/interactive/commands.ex
- lib/mix/tasks/sse.interactive.ex
- lib/mix/tasks/stdio.interactive.ex
- pages/cli_usage.md
Logging across the library lacked proper verbosity controls and didn't correctly
respect configured log levels, making it difficult to debug certain issues.
- Added customizable log levels with proper semantics
- Implemented CLI verbose flags with accumulation (-v, -vv, -vvv)
- Fixed metadata preservation in all logger calls
- Updated documentation with usage examples
Command-line tools need flexible verbosity controls to aid in troubleshooting while
maintaining clean output by default. The accumulated verbose flag pattern (-v, -vv,
-vvv) provides an intuitive interface that's familiar to users.
> feat: improve log handling on core lib and interactive/cli

- lib/hermes/client.ex
- pages/client_usage.md
- test/hermes/client_test.exs
- Client used two unsynchronized timeouts: operation timeout and GenServer.call timeout
- When GenServer.call timed out first, client couldn't identify which request failed
- No cancellation notification was sent to server
- Client crashed with GenServer timeout instead of clean request timeout error
- Added buffer to GenServer.call timeouts: `operation.timeout + to_timeout(second: 1)`
- Ensures operation timeout triggers first, allowing proper request identification
- Enables sending cancellation notifications before GenServer timeout
- Updated @spec directives and documentation
- Added test verifying buffer timeout functionality
Close #69, #66 and the old #42
- Added test that confirms operation timeout triggers before GenServer timeout
- Verified clean error handling without GenServer …
> fix: nested timeout

- lib/hermes/client.ex
- lib/hermes/logging.ex
- lib/hermes/transport/sse.ex
Issue #75 requests the ability to suppress Hermes client logging. Currently, transport
layers (STDIO, SSE, WebSocket) emit debug logs for every message sent/received,
creating noise in production environments. Users cannot disable these internal logs
without changing their global Logger configuration, which affects their entire
application.
Added a :log configuration option to suppress all Hermes internal logging. When set to
false, the Hermes.Logging module skips all log calls, preventing transport events and
MCP message logs from being emitted.
```elixir
import Config
config :hermes, log: false
```
Follows the established pattern used by other Elixir libraries like Ecto (log: false)
and Oban (log: false). This approach provides a simple, library-specific configuration
that doesn't …
> feat: enable log disabling

- justfile
- lib/hermes.ex
- lib/hermes/server.ex
- lib/hermes/server/base.ex
- lib/hermes/server/handlers/prompts.ex
- lib/hermes/server/handlers/resources.ex
- lib/hermes/server/handlers/tools.ex
- lib/hermes/server/response.ex
- priv/dev/upcase/lib/upcase/prompts/text_transform.ex
- priv/dev/upcase/lib/upcase/resources/examples.ex
- priv/dev/upcase/lib/upcase/tools/analyze_text.ex
- priv/dev/upcase/lib/upcase/tools/upcase.ex
The MCP server implementation had duplicated handler logic within the Hermes.Server module's __using__ macro, making the code
harder to maintain and extend. Handler methods for tools, prompts, and resources were embedded directly in the generated
handle_request/2 function.
Extracted the handler logic into dedicated handler modules under Hermes.Server.Handlers namespace:
- Hermes.Server.Handlers.Tools - handles tools/list and tools/call
- Hermes.Server.Handlers.Prompts - handles prompts/list and prompts/get
- Hermes.Server.Handlers.Resources - handles resources/list and resources/read
The default handle_request/2 implementation now simply pattern matches on the method and delegates to the appropriate handler
module.
This refactoring improves code organization by:
1. Following single …
> feat: mcp server handlers refactored

- .formatter.exs
- .github/workflows/ci.yml
- .github/workflows/release-please.yml
- .github/workflows/release.yml
- CLAUDE.md
- lib/hermes/server/component.ex
- lib/hermes/server/component/schema.ex
- pages/server_components.md
- test/hermes/server/component/schema_test.exs
- test/hermes/server/component_field_macro_test.exs
- test/hermes/server/component_prompt_test.exs
- test/support/test_tools.ex
The MCP protocol requires JSON Schema format for tool input schemas, but Peri (our validation library) doesn't support JSON
Schema metadata like format and description fields. This limits the ability to provide rich documentation and validation hints
to MCP clients.
Closes #95
Added a field/2 and field/3 macro that wraps Peri types with metadata using :mcp_field tuples. The implementation:
- Stores raw schema with metadata in __mcp_raw_schema__() for JSON Schema generation
- Strips metadata for Peri validation using __clean_schema_for_peri__/1
- Supports nested fields with clean syntax (no explicit map braces needed)
- Works for both tools and prompts
Maintained an in-house solution rather than modifying Peri to keep the implementation simple and avoid upstream dependencies.
The dual …
> feat: allow json schema fields on tools/prompts definition

- lib/hermes/logging.ex
- test/hermes/logging_test.exs
The Hermes MCP logging system had hardcoded log levels for different event types. Specially the ping is quite verbose.
Definitely there is value in all of them just not all the time when we are implementing an higher level functionality.
Added configurable default log levels for different event types through application configuration. Users can now independently set log levels
for:
- client_events - client lifecycle events
- server_events - server lifecycle events
- transport_events - transport layer events
- protocol_messages - MCP protocol messages
The configuration allows fine-grained control over logging verbosity:
```elixir
config :hermes_mcp, :logging,
client_events: :info,
server_events: :info,
transport_events: :debug,
protocol_messages: :debug
```
This approach maintains backward …
> feat: add independently configurable logs

- lib/hermes/client.ex
`client_info` and `capabilities` weren't being escaped correctly, blocking modules to compile when `use Hermes.Client`
Escape the missing expressions
Close #118
> fix: correctly escape quoted expressions

- CLAUDE.md
- lib/hermes/client/base.ex
- lib/hermes/client/state.ex
- lib/hermes/mcp/message.ex
- lib/hermes/server/base.ex
- lib/hermes/server/component.ex
- lib/hermes/server/component/tool.ex
- lib/hermes/server/handlers/tools.ex
- test/hermes/client/base_test.exs
- test/hermes/client/batch_test.exs
- test/hermes/server/base_test.exs
- test/hermes/server/component/tool_annotations_test.exs
- test/hermes/server/transport/streamable_http/plug_test.exs
This pull request introduces enhancements to the Hermes framework, focusing on protocol version compatibility, annotations for tools, and improved handling of progress tokens. Additionally, it updates documentation and tests to reflect these changes.
* [`lib/hermes/client/base.ex`](diffhunk://#diff-bfaef6ab59ba5bb96855ede4ff713c9f7923f2fc2937f45031f1f33f3e3f009aR850): Added checks to ensure batch operations are only supported for protocol versions `2025-03-26` or later. Returns an error for unsupported versions. [[1]](diffhunk://#diff-bfaef6ab59ba5bb96855ede4ff713c9f7923f2fc2937f45031f1f33f3e3f009aR850) [[2]](diffhunk://#diff-bfaef6ab59ba5bb96855ede4ff713c9f7923f2fc2937f45031f1f33f3e3f009aR860-R870)
* [`lib/hermes/server/base.ex`](diffhunk://#diff-1146a134b004c3f80ca5063ac01c480f7a3364c39d …
> feat: tools annotations

- lib/hermes/client/base.ex
- lib/hermes/server.ex
- lib/hermes/server/base.ex
- lib/hermes/server/session.ex
- lib/hermes/telemetry.ex
This pull request introduces several enhancements to the `Hermes` module, primarily focused on improving notification handling, tracking pending requests, and extending telemetry capabilities. The changes aim to streamline server-client communication, enhance request lifecycle tracking, and provide better observability through telemetry.
* Added new private functions in `Hermes.Client.Base` to handle various notifications (`resources/list_changed`, `resources/updated`, `prompts/list_changed`, `tools/list_changed`) and log telemetry events accordingly. (`[[1]](diffhunk://#diff-bfaef6ab59ba5bb96855ede4ff713c9f7923f2fc2937f45031f1f33f3e3f009aR1294-R1309)`, `[[2]](diffhunk://#diff-bfaef6ab59ba5bb96855ede4ff713c9f7923f2fc2937f45031f1f33f3e3f009aR1375-R1424)`)
* Introduced public functions in …
> feat: missing notifications handlers

- lib/hermes/server/base.ex
- lib/hermes/server/transport/sse/plug.ex
- lib/hermes/server/transport/streamable_http/plug.ex
- test/hermes/server/transport/sse/plug_test.exs
- test/hermes/server/transport/streamable_http/plug_test.exs
- test/support/mock_custom_registry.ex
There are leftover hardcoded `Hermes.Server.Registry` in transport plugs and the base server. This was preventing me from using a custom Horde-based registry, causing `ArgumentError: unknown registry` errors in multi-node setups.
I have verified that this solution works in production using our fork.
- Added optional `registry` parameter to `Hermes.Server.Transport.SSE.Plug` and `Hermes.Server.Transport.StreamableHTTP.Plug`. The parameter defaults to `Hermes.Server.Registry` for backward compatibility.
- Updated `Hermes.Server.Base` to pass registry to session management.
**Usage:**
```elixir
get "/sse", Hermes.Server.Transport.SSE.Plug,
server: MyServer, mode: :sse
get "/sse", Hermes.Server.Transport.SSE.Plug,
server: MyServer, mode: :sse, registry: MyApp.HordeRegistry
```
This seemed …
> Remove last uses of hard-coded Hermes.Server.Registry

- lib/hermes/server.ex
- priv/dev/upcase/lib/upcase/server.ex
The current Hermes.Server implementation doesn't support callback-based server definitions. When users try to implement
server_info/0, server_capabilities/0, or supported_protocol_versions/0 callbacks directly, they get compile-time errors because
the macro tries to validate and define these functions before the user's implementations are available.
- Moved validation logic from compile-time to @before_compile and @after_compile hooks
- Check if callbacks are already defined using Module.defines?/2 before generating default implementations
- Only validate server info if the user hasn't implemented the callback and hasn't provided macro options
- Made the macro options truly optional, allowing users to define all server metadata via callbacks
The original implementation assumed all servers …
> fix: correctly allows macro-based/callback-based server implementations

- lib/hermes/server.ex
- lib/hermes/server/component.ex
- lib/hermes/server/component/schema.ex
- pages/server_components.md
The current server component schema definition syntax is verbose and inconsistent. Required fields need to be wrapped with
{:required, type} which makes the schema harder to read and maintain. Additionally, the schema system lacks built-in support for
date/time types, requiring manual string validation.
This PR introduces a cleaner Peri integration with two key improvements:
1. Simplified required field syntax: Added a required: true option to the field macro, eliminating the need for {:required,
type} wrapping
2. Native date/time type support: Added automatic validation and parsing for :date, :time, :datetime, and :naive_datetime types
that convert ISO 8601 strings to Elixir structs
The changes improve developer experience by:
- Making schemas more readable and consistent with typical …
> refactor: cleaner peri integration

- README.md
- lib/hermes/server/supervisor.ex
- pages/error_handling.md
- pages/progress_tracking.md
- pages/server_components.md
- pages/server_quickstart.md
`sse` and `streamable_http` transport can have additional options passed as a tuple into the child_spec of supervision tree.
so users was being requried to pass `{:sse, []}` if no additional options is needed, causing confusion about how to configure transport layer, conflicting with the simple `:stdio`
normalize the transport, so users can now pass only `transport: :sse` or `transport: :streamable_http`
Close #145
> fix: normalize transport api

- lib/hermes.ex
- lib/hermes/server.ex
- lib/hermes/server/base.ex
- lib/hermes/server/component/prompt.ex
- lib/hermes/server/component/resource.ex
- lib/hermes/server/component/tool.ex
- lib/hermes/server/frame.ex
- lib/hermes/server/handlers/prompts.ex
- lib/hermes/server/handlers/resources.ex
- lib/hermes/server/handlers/tools.ex
- lib/hermes/server/session.ex
- lib/hermes/server/supervisor.ex
- priv/dev/ascii/lib/ascii/mcp_server.ex
- priv/dev/echo-elixir/lib/echo_mcp/server.ex
- priv/dev/upcase/lib/upcase/server.ex
- test/hermes/server/base_test.exs
- test/hermes/server/component/tool_annotations_test.exs
- test/hermes/server/transport/sse/plug_test.exs
- test/hermes/server/transport/streamable_http/plug_test.exs
- test/support/mcp/setup.ex
- test/support/stub_server.ex
The current MCP server implementation requires components (tools, resources, prompts) to be defined as modules at compile-time,
limiting flexibility and making it difficult to dynamically register components based on runtime conditions.
- Introduced runtime component registration through the Frame API (Frame.register_tool/3, Frame.register_resource/3,
Frame.register_prompt/3)
- Added new server callbacks (handle_tool_call/3, handle_resource_read/3, handle_prompt_get/3) for granular request handling
- Converted components from behaviors to structs with JSON.Encoder implementations
- Moved server initialization to MCP handshake phase instead of GenServer startup
This hybrid approach maintains backward compatibility with module-based components while enabling dynamic component
registration. …
> feat: runtime server components, simplified api

- lib/hermes/client/base.ex
- lib/hermes/http.ex
- lib/hermes/logging.ex
- lib/hermes/server/base.ex
- lib/hermes/server/transport/sse.ex
- lib/hermes/server/transport/sse/plug.ex
- lib/hermes/server/transport/stdio.ex
- lib/hermes/server/transport/streamable_http.ex
- lib/hermes/server/transport/streamable_http/plug.ex
- lib/hermes/sse.ex
- lib/hermes/sse/streaming.ex
- lib/hermes/transport/sse.ex
- lib/hermes/transport/stdio.ex
- lib/hermes/transport/streamable_http.ex
- lib/hermes/transport/websocket.ex
- pages/logging.md
- test/hermes/logging_test.exs
`Hermes.Logging` functions were appearing as the log source instead of the actual caller module/function. `Logger` metadata showed incorrect source location.
Converted logging functions to macros to capture caller metadata via Logger's built-in `__CALLER__` mechanism. Fixed level comparison logic and test expectations.
Macros execute in the caller's context, allowing `Logger` to automatically inject correct file/line/module metadata. This approach leverages Elixir's existing infrastructure rather than manually tracking metadata.
> fix: loggin should respect the logger config

- lib/hermes/server/component/schema.ex
- pages/server_components.md
- test/hermes/server/component/schema_test.exs
This pull request enhances support for numeric constraints in the `Hermes.Server.Component.Schema` module by introducing new constraint types for integers and floats. It also updates the documentation and tests to reflect these changes.
* Added support for new integer constraints: `{:eq, value}`, `{:neq, value}`, `{:gt, value}`, `{:gte, value}`, `{:lt, value}`, and `{:lte, value}`. These map to JSON Schema properties like `const`, `not`, `exclusiveMinimum`, and `exclusiveMaximum`.
* Added support for equivalent float constraints: `{:eq, value}`, `{:neq, value}`, `{:gt, value}`, `{:gte, value}`, `{:lt, value}`, and `{:lte, value}`.
* Updated `pages/server_components.md` to document the new integer and float constraints, including examples for each.
* Expanded tests in …
> fix: correctly parse peri numeric contrainsts to json-schema

- .github/workflows/ci.yml
- lib/mix/tasks/sse.interactive.ex
- lib/mix/tasks/streamable_http.interactive.ex
This pull request introduces support for custom headers in two Mix tasks (`hermes.sse.interactive` and `hermes.streamable_http.interactive`). The changes allow users to specify multiple headers for HTTP requests, improving flexibility and configurability. Key updates include the addition of a `--header` option, parsing logic for headers, and integration of headers into the request configuration.
* Added a `--header` option to allow users to specify custom headers for SSE requests, with examples provided in the documentation.
* Updated the `@switches` definition to include the `:header` option with the `:keep` modifier, enabling multiple values.
* Integrated a `parse_headers` function to process the `--header` values into a map of header key-value pairs.
* Modified the configuration setup …
> fix: interactive http tasks should accept custom headers

- lib/hermes/server.ex
- lib/hermes/server/base.ex
- lib/hermes/server/frame.ex
- lib/hermes/server/session.ex
- test/hermes/server/base_test.exs
helper functions for servers send notifications were implemented as handle_call/handle_cast on the Base module, which causes a deadlock, raising a "process tried to call itself" exception
move those helpers to the Server module and send messages as handle_info to the Base process, that way it can handle it correctly
N/A
> fix: server can now send notifications correctly

- lib/hermes/client/base.ex
- lib/hermes/client/state.ex
- lib/hermes/mcp/message.ex
- test/hermes/client/base_test.exs
- test/support/mcp/setup.ex
This pull request introduces a new feature to handle "sampling/createMessage" requests in the Hermes client, along with associated changes to support this functionality. Key updates include adding a sampling callback mechanism, extending the message schema, and updating the client state and tests.
* Added a new method `register_sampling_callback` to allow clients to register a callback for handling "sampling/createMessage" requests. This includes a corresponding method to unregister the callback. (`lib/hermes/client/base.ex`, [[1]](diffhunk://#diff-bfaef6ab59ba5bb96855ede4ff713c9f7923f2fc2937f45031f1f33f3e3f009aR732-R780) [[2]](diffhunk://#diff-bfaef6ab59ba5bb96855ede4ff713c9f7923f2fc2937f45031f1f33f3e3f009aR879-R886)
* Implemented server request handling for "sampling/createMessage", …
> feat: client sampling capability

- lib/hermes/server.ex
- lib/hermes/server/frame.ex
- lib/hermes/server/handlers.ex
- lib/hermes/server/handlers/prompts.ex
- lib/hermes/server/handlers/resources.ex
- lib/hermes/server/handlers/tools.ex
- priv/dev/upcase/lib/upcase/server.ex
- test/hermes/server/handlers_test.exs
This pull request introduces pagination support for listing operations (`tools`, `prompts`, and `resources`) in the `Hermes.Server` module. It also includes refactoring to improve code maintainability and adds comprehensive test coverage for the new functionality.
* Added a `pagination_limit` field to the `Frame` struct and a new function `put_pagination_limit/2` to set this limit. This controls the maximum number of items returned in listing operations. (`lib/hermes/server/frame.ex`, [[1]](diffhunk://#diff-d296c5fa6a67da6ccd1e72c33584efa89ff5de71e9741185421804b20e16cac6R72-R74) [[2]](diffhunk://#diff-d296c5fa6a67da6ccd1e72c33584efa89ff5de71e9741185421804b20e16cac6R260-R281)
* Implemented the `maybe_paginate/3` function in `Handlers` to handle cursor-based pagination for listing …
> feat: server components cursor pagination

- lib/hermes/server.ex
- lib/hermes/server/base.ex
- lib/hermes/server/handlers.ex
- lib/hermes/server/handlers/completion.ex
- lib/hermes/server/response.ex
The Hermes MCP server implementation was missing several features from the latest MCP specification (2025-06-18), including:
- Completion support (completion/complete)
- Roots list capability (roots/list request from server to client)
Implemented the missing MCP features:
1. Completion support: Added completion handler, extended Response module to support completion responses, and updated server
capabilities
2. Roots list: Added ability for server to query client for available root URIs with timeout and cancellation support
- Followed existing patterns in the codebase for consistency
- Used the Response builder pattern for completion responses
- Modeled roots/list after the existing sampling request pattern but simplified by removing unnecessary metadata parameter
> feat: roots/list and completion features

- lib/hermes/server/frame.ex
This pull request refines the logic for managing components within the `Hermes.Server.Frame` module by introducing a helper function to ensure unique identification of components.
Enhancements to component management:
* [`lib/hermes/server/frame.ex`](diffhunk://#diff-d296c5fa6a67da6ccd1e72c33584efa89ff5de71e9741185421804b20e16cac6L511-R515): Replaced the uniqueness logic in `update_components/2` by introducing a new helper function `unique_component/1`. This function uniquely identifies components using a tuple of their struct and name, improving clarity and maintainability.
> chore: allow different kind of components have the same name

- lib/hermes/server/supervisor.ex
- lib/hermes/server/transport/sse.ex
- lib/hermes/server/transport/stdio.ex
- lib/hermes/server/transport/streamable_http.ex
This pull request introduces enhancements to the Hermes server and its transport modules by adding support for configurable request timeouts. The changes ensure that timeout values can be customized for server requests and batch operations, improving flexibility and reliability across different transport implementations.
* Updated `start_option` type in `lib/hermes/server/supervisor.ex` to include `:request_timeout` and `:server_name`, allowing configuration of server request timeouts and custom server names.
* Modified child initialization logic to pass the `request_timeout` option to transport processes.
* Added `:request_timeout` as a required schema option and integrated it into the transport state. [[1]](diffhunk://#diff-55b06b7bd9573939a623c1ed37d5f44e300842a5b8cdecfde8fbfb141613a447 …
> fix: allow configuring server request timeout

- .github/workflows/publish.yml
This pull request adds a new GitHub Actions workflow for publishing Elixir packages to Hex. The workflow automates testing, formatting checks, static analysis, and publishing when a new tag matching the `v*` pattern is pushed.
* [`.github/workflows/publish.yml`](diffhunk://#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7R1-R65): Introduced a `Publish to Hex` workflow triggered by tag pushes (`v*`). The workflow includes steps for setting up Elixir, caching dependencies and builds, installing and compiling dependencies, running tests, checking formatting, performing static code analysis using Credo, and publishing the package to Hex.
> config: publish to hex ci action

- lib/hermes/protocol.ex
- lib/hermes/server/transport/stdio.ex
- lib/hermes/server/transport/streamable_http.ex
- lib/hermes/transport/behaviour.ex
- lib/hermes/transport/stdio.ex
- lib/hermes/transport/streamable_http.ex
- lib/hermes/transport/websocket.ex
- test/support/mock_transport.ex
- test/support/stub_transport.ex
This pull request refactors how protocol version compatibility is handled across transports in the Hermes system. It introduces a new mechanism for specifying supported protocol versions, updates the behavior definition, and modifies several transport modules to align with the new approach.
* [`lib/hermes/protocol.ex`](diffhunk://#diff-98232ed245d0a2546cad3d194c94fd8e637e46a66416b40a5d067ae1850522dbL81-R102): Added the `supported_transport_versions/1` private function to handle cases where a transport specifies `:all` as its supported protocol versions, mapping it to the global `@supported_versions`. Updated the `validate_transport/2` function to use this new mechanism.
* [`lib/hermes/transport/behaviour.ex`](diffhunk://#diff-71dc0b3f96d79ae5f656538529828d6dbcc9c2cb2f58b5d938b51fdc06851cad …
> fix: correctly set supported versions for different transports

- lib/hermes/server/base.ex
- lib/hermes/server/session.ex
- pages/building-a-server.md
This pull request refactors the `Hermes.Server.Base` module to improve state formatting and logging while removing sensitive data redaction logic. Additionally, it introduces a custom `Inspect` implementation for `Hermes.Server.Session` and updates documentation to reflect these changes.
* [`lib/hermes/server/base.ex`](diffhunk://#diff-1146a134b004c3f80ca5063ac01c480f7a3364c39d4ce152f102e24db0f18673L306-R349): Replaced the `sanitize_state` function with `format_state`, which formats the server state for better readability and includes new helper functions like `format_pending_requests` and `format_sessions`. Removed sensitive data redaction logic, simplifying the codebase. [[1]](diffhunk://#diff-1146a134b004c3f80ca5063ac01c480f7a3364c39d4ce152f102e24db0f18673L306-R349) …
> fix: remove assign redact feature, simplify server state inspect

- lib/hermes/client/base.ex
- lib/hermes/client/operation.ex
- lib/hermes/transport/streamable_http.ex
- test/hermes/transport/streamable_http_test.exs
Currently we are not propagating / accepting headers for StreamableHttp transport
Implementation of header optional param
Will be handled only for StreamableHTTP for now.
> feat: propagating headers on requests

- lib/hermes/client/base.ex
- lib/hermes/server/transport/sse.ex
- lib/hermes/server/transport/stdio.ex
- lib/hermes/server/transport/streamable_http.ex
- lib/hermes/transport/behaviour.ex
- lib/hermes/transport/sse.ex
- lib/hermes/transport/stdio.ex
- lib/hermes/transport/streamable_http.ex
- lib/hermes/transport/websocket.ex
- test/hermes/client/base_test.exs
- test/hermes/server/transport/sse_test.exs
- test/hermes/server/transport/stdio_test.exs
- test/hermes/server/transport/streamable_http_test.exs
- test/hermes/transport/sse_test.exs
- test/hermes/transport/stdio_test.exs
- test/hermes/transport/websocket_test.exs
- test/support/mock_transport.ex
- test/support/stub_transport.ex
Currently, method `GenServer.call` used on transports have a default timeout of 5s.
Despite allowing to pass http options such as the timeout to be used in the request, the GenServer will throw a timeout after 5s.
Use a timeout param on `GenServer.call` from opts
opts will allow us to propagate any other config in the future
> feat: propagating opts from client.base
